// Generated by tools/make_mark.py — do not edit.
//
// The status-item numbers, in the item's own points, straight from the artwork
// that drew MenuBarMark.pdf. Variant B: the bead sits beside the glyph and its
// space is reserved in both states, so the letter never hops.

import CoreGraphics

enum LoreMarkGeometry {
    /// The status-item drawing box — glyph and bead together.
    static let statusBox = CGSize(width: 16, height: 18)

    /// Bead diameter at a 16pt status item, not the 8pt of the in-window dot.
    static let beadSize: CGFloat = 3.2

    /// Bead centre inside `statusBox`, measured from its top-left.
    static let beadCenter = CGPoint(x: 11.748, y: 8.600)
}
