import AppKit
import XCTest
@testable import LoreKit

/// Word boundaries for a placement test: when each word ended, and which of
/// them a clause ended at. Free-standing so both rich-input cases share it.
func spokenWords(_ ends: [Double], endingClauseAt clauses: Set<Int> = []) -> [RichInput.Word] {
    ends.enumerated().map { RichInput.Word(end: $1, endsClause: clauses.contains($0)) }
}

/// Rich input (#192), the parts that are pure: what the clipboard door accepts,
/// where an item lands in the words, what the paste says, and how the words come
/// back out for cleanup with the items untouched.
@MainActor
final class RichInputTests: XCTestCase {

    // MARK: - Classification

    private func type(_ raw: String) -> NSPasteboard.PasteboardType {
        NSPasteboard.PasteboardType(raw)
    }

    func testCopiedTextIsATextItem() {
        XCTAssertEqual(ClipboardWatcher.kind(for: [.string]), .text)
    }

    func testScreenshotToClipboardIsAnImageItem() {
        XCTAssertEqual(ClipboardWatcher.kind(for: [.png]), .image)
        XCTAssertEqual(ClipboardWatcher.kind(for: [.tiff]), .image)
    }

    func testFinderCopyIsAFileItemEvenWhenItAlsoCarriesTextAndURL() {
        XCTAssertEqual(ClipboardWatcher.kind(for: [.fileURL, .URL, .string]), .fileURL)
    }

    func testImageBeatsURLAndText() {
        XCTAssertEqual(ClipboardWatcher.kind(for: [.png, .URL, .string]), .image)
    }

    func testURLBeatsText() {
        XCTAssertEqual(ClipboardWatcher.kind(for: [.URL, .string]), .url)
    }

    /// Password managers mark their copies; a marked copy is never added, never
    /// shown, never counted — whatever else it carries.
    func testConcealedCopyIsNothingAtAll() {
        for marker in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ] {
            XCTAssertNil(
                ClipboardWatcher.kind(for: [.string, type(marker)]),
                "a copy marked \(marker) must not become an item"
            )
        }
    }

    func testTypesWithNoFormAreNotItems() {
        XCTAssertNil(ClipboardWatcher.kind(for: [.pdf]))
        XCTAssertNil(ClipboardWatcher.kind(for: []))
    }

    /// Structure, not meaning: one line, no whitespace, an http(s) address with
    /// a host. Everything else the user copied is what he copied.
    func testWhatCountsAsALinkIsStructural() {
        for link in [
            "https://open.spotify.com/track/2xLMifQCjDGFmkHkpNLD9h",
            "http://127.0.0.1:4747/rituals",
            "  https://example.com/a?b=c#d  ",
        ] {
            XCTAssertTrue(ClipboardWatcher.isLink(link), link)
        }
        for text in [
            "see https://example.com",
            "https://example.com and more",
            "https://example.com\nhttps://example.com",
            "example.com",
            "file:///Users/a/notes.md",
            "mailto:a@example.com",
            "https://",
            "",
        ] {
            XCTAssertFalse(ClipboardWatcher.isLink(text), text)
        }
    }

    // MARK: - The door, against a real pasteboard nobody else can see

    /// A pasteboard nobody else can see, so a test never touches the user's
    /// clipboard.
    private var board: NSPasteboard!

    // `async throws`, not the plain overrides: `XCTestCase.setUp()` is
    // nonisolated, so a nonisolated override in this `@MainActor` class cannot
    // touch `board`. The async pair inherits the class's isolation — the shape
    // every other @MainActor case here already uses.
    override func setUp() async throws {
        board = NSPasteboard(name: NSPasteboard.Name("com.lore.tests.\(UUID().uuidString)"))
        // The door reads the Copying switches live (#198); on this machine the
        // owner's own Settings would otherwise decide whether these pass.
        _ = isolatedRichInputDefaults("RichInputTests")
    }

    override func tearDown() async throws {
        RichInputSettings.use(.standard)
        board.releaseGlobally()
        board = nil
    }

    /// Seeds the change count the way a confirmed hold does, then stops the
    /// poll so the test steps the loop itself.
    private func startedWatcher() -> ClipboardWatcher {
        let watcher = ClipboardWatcher(pasteboard: board)
        watcher.start(offset: { 0 }, onItem: { _ in })
        watcher.stop()
        return watcher
    }

    func testACopyDuringTheRecordingBecomesOneItemAtItsOwnMoment() {
        let watcher = startedWatcher()
        board.clearContents()
        board.setString("the issue already says it", forType: .string)

        let item = watcher.collect(at: 31.2)
        XCTAssertEqual(item?.kind, .text)
        XCTAssertEqual(item?.text, "the issue already says it")
        XCTAssertEqual(item?.offset ?? 0, 31.2, accuracy: 0.001)
        XCTAssertEqual(item?.included, true)

        // Nothing changed since — no second item for the same copy.
        XCTAssertNil(watcher.collect(at: 31.3))
    }

    /// Lore's own writes are its own; they never come back as material.
    func testLoresOwnPasteIsNeverCollected() {
        let watcher = startedWatcher()
        board.clearContents()
        board.setString("what lore just pasted", forType: .string)
        PasteboardWriteLedger.shared.note(board.changeCount)

        XCTAssertNil(watcher.collect(at: 2.0))
    }

    /// Spotify's "copy link" writes plain text and no `public.url` — the types
    /// cannot tell a link from a sentence, so the text is read.
    func testACopiedLinkWithNoURLTypeIsStillALink() {
        let watcher = startedWatcher()
        board.clearContents()
        board.setString("https://open.spotify.com/track/2xLMifQCjDGFmkHkpNLD9h", forType: .string)

        let item = watcher.collect(at: 4.0)
        XCTAssertEqual(item?.kind, .url)
        XCTAssertEqual(
            item?.pasteText,
            "<link>https://open.spotify.com/track/2xLMifQCjDGFmkHkpNLD9h</link>"
        )
    }

    /// A sentence that happens to mention an address is copied text, tagged as
    /// what it is.
    func testCopiedProseThatMentionsALinkStaysText() {
        let watcher = startedWatcher()
        board.clearContents()
        board.setString("look at https://example.com", forType: .string)

        XCTAssertEqual(watcher.collect(at: 4.0)?.kind, .text)
    }

    func testWhatWasOnTheClipboardBeforeTheRecordingIsNotAnItem() {
        board.clearContents()
        board.setString("copied yesterday", forType: .string)

        XCTAssertNil(startedWatcher().collect(at: 1.0))
    }

    // MARK: - Position

    private func token(_ text: String, _ start: Double, _ end: Double) -> TranscribedToken {
        TranscribedToken(text: text, start: start, end: end)
    }

    func testWordsFollowSubWordTokens() {
        let tokens = [
            token(" hel", 0.0, 0.2), token("lo", 0.2, 0.4),
            token(" wor", 0.4, 0.6), token("ld.", 0.6, 0.9),
        ]
        let words = RichInput.words(tokens: tokens, audioOffset: 0)
        XCTAssertEqual(words.map(\.end), [0.4, 0.9])
        // "hello" runs into "world" with no pause and no punctuation; "world."
        // carries its own full stop.
        XCTAssertEqual(words.map(\.endsClause), [false, true])
    }

    /// The instant falls between two words of one phrase — the real case that
    /// wedged a screenshot between "чёрный" and "квадрат". The item waits for
    /// the comma.
    func testAnItemTakenMidPhraseLandsAtTheEndOfTheClause() {
        let tokens = [
            token(" вот", 0.0, 0.4), token(" чёрный", 0.4, 1.0),
            token(" квадрат,", 1.0, 1.6), token(" посмотри", 1.6, 2.2),
        ]
        let words = RichInput.words(tokens: tokens, audioOffset: 0)
        XCTAssertEqual(words.map(\.endsClause), [false, false, true, false])

        let item = DictationItem(kind: .image, offset: 1.05, path: "/Users/a/x-0.png")
        XCTAssertEqual(
            RichInput.compose(
                spoken: "вот чёрный квадрат, посмотри", items: [item], words: words
            ),
            "вот чёрный квадрат,\n\n<screenshot>/Users/a/x-0.png</screenshot>\n\nпосмотри"
        )
    }

    /// A pause long enough to hear ends a clause the recogniser wrote no
    /// punctuation for. A full second of it: half a second is the hesitation
    /// inside a sentence.
    func testASecondOfSilenceEndsAClauseWithoutPunctuation() {
        let tokens = [token(" so", 0.0, 0.3), token(" look", 0.3, 0.8), token(" here", 1.9, 2.4)]
        let words = RichInput.words(tokens: tokens, audioOffset: 0)
        XCTAssertEqual(words.map(\.endsClause), [false, true, false])

        let item = DictationItem(kind: .url, offset: 0.4, text: "https://example.com")
        XCTAssertEqual(
            RichInput.compose(spoken: "so look here", items: [item], words: words),
            "so look\n\n<link>https://example.com</link>\n\nhere"
        )
    }

    /// The real case behind the threshold: an "uh" and a breath while the
    /// speaker reached for the next word. The screenshot taken during it
    /// belongs after the sentence, not in the middle of it.
    func testAHesitationIsNotTheEndOfAClause() {
        let tokens = [token(" put", 0.0, 0.3), token(" uh", 0.3, 0.8), token(" cover.", 1.3, 1.8)]
        let words = RichInput.words(tokens: tokens, audioOffset: 0)
        XCTAssertEqual(words.map(\.endsClause), [false, false, true])

        let item = DictationItem(kind: .image, offset: 0.9, path: "/Users/a/x-0.png")
        XCTAssertEqual(
            RichInput.compose(spoken: "put uh cover.", items: [item], words: words),
            "put uh cover.\n\n<screenshot>/Users/a/x-0.png</screenshot>"
        )
    }

    /// A dictation past 30 s is two chunks, and the second chunk's timings are
    /// its own — the offset has to come back.
    func testAnItemPastTheChunkBoundaryLandsInTheSecondChunksWords() {
        let first = [token(" one", 0.0, 0.5), token(" two", 0.5, 1.0)]
        let second = [token(" three,", 0.1, 0.6), token(" four", 0.6, 1.2)]
        let words = RichInput.words(tokens: first, audioOffset: 0)
            + RichInput.words(tokens: second, audioOffset: 30)
        XCTAssertEqual(words.map(\.end), [0.5, 1.0, 30.6, 31.2])

        let item = DictationItem(kind: .text, offset: 30.7, text: "COPIED")
        XCTAssertEqual(
            RichInput.compose(spoken: "one two three, four", items: [item], words: words),
            "one two three,\n\n<copied>\nCOPIED\n</copied>\n\nfour"
        )
    }

    func testWithoutTimingsAnItemGoesToTheEnd() {
        let item = DictationItem(kind: .url, offset: 1.0, text: "https://example.com")
        XCTAssertEqual(
            RichInput.compose(spoken: "look at this", items: [item], words: []),
            "look at this\n\n<link>https://example.com</link>"
        )
    }

    /// Speech that never comes to a clause after the instant: the end of the
    /// text is the honest place, and it is still not earlier than the instant.
    func testAnItemWithNoClauseLeftGoesToTheEnd() {
        let item = DictationItem(kind: .text, offset: 0.6, text: "COPIED")
        XCTAssertEqual(
            RichInput.compose(
                spoken: "one two three", items: [item], words: spokenWords([0.5, 1.0, 1.5])
            ),
            "one two three\n\n<copied>\nCOPIED\n</copied>"
        )
    }

    // MARK: - Compose

    /// Every kind says what it is, and a path is not quoted — the tag is the
    /// fence a name with spaces in it needs.
    func testEachKindIsTaggedForWhatItIs() {
        XCTAssertEqual(
            DictationItem(kind: .text, offset: 0, text: "two\nlines").pasteText,
            "<copied>\ntwo\nlines\n</copied>"
        )
        XCTAssertEqual(
            DictationItem(kind: .url, offset: 0, text: "https://example.com").pasteText,
            "<link>https://example.com</link>"
        )
        XCTAssertEqual(
            DictationItem(kind: .image, offset: 0, path: "/Users/a/Screenshot 13.41.02.png")
                .pasteText,
            "<screenshot>/Users/a/Screenshot 13.41.02.png</screenshot>"
        )
        XCTAssertEqual(
            DictationItem(kind: .fileURL, offset: 0, path: "/Users/a/notes 2026.md").pasteText,
            "<file>/Users/a/notes 2026.md</file>"
        )
        // A picture whose file could not be written names nothing.
        XCTAssertNil(DictationItem(kind: .image, offset: 0).pasteText)
    }

    /// The diagnostic stream may carry the size, never the content (#82) — and
    /// the size of words is their UTF-8 length, not zero.
    func testAnItemReportsItsOwnByteCount() {
        XCTAssertEqual(DictationItem(kind: .text, offset: 1, text: "привет").byteCount, 12)
        XCTAssertEqual(
            DictationItem(kind: .url, offset: 1, text: "https://example.com").byteCount, 19
        )
        XCTAssertEqual(DictationItem(kind: .fileURL, offset: 1, path: "/tmp/a.md").byteCount, 9)
        XCTAssertEqual(
            DictationItem(kind: .image, offset: 1, path: "/tmp/x.png", imageData: Data(count: 4510))
                .byteCount,
            4510
        )
    }

    func testAScreenshotIsATaggedPathOnItsOwnLines() {
        let item = DictationItem(
            kind: .image, offset: 0.6, path: "/Users/a/Lore/RichInput/x-0.png"
        )
        XCTAssertEqual(
            RichInput.compose(
                spoken: "look at this.", items: [item],
                words: spokenWords([0.3, 0.6, 0.9], endingClauseAt: [2])
            ),
            "look at this.\n\n<screenshot>/Users/a/Lore/RichInput/x-0.png</screenshot>"
        )
    }

    func testACopiedFileIsItsPath() {
        let item = DictationItem(kind: .fileURL, offset: 0.4, path: "/Users/a/notes 2026.md")
        XCTAssertEqual(
            RichInput.compose(
                spoken: "open it.", items: [item],
                words: spokenWords([0.4, 0.8], endingClauseAt: [1])
            ),
            "open it.\n\n<file>/Users/a/notes 2026.md</file>"
        )
    }

    func testAnItemSwitchedOffLeavesNoTrace() {
        var item = DictationItem(kind: .text, offset: 0.4, text: "PASTED")
        item.included = false
        let spoken = "one two three"
        XCTAssertEqual(
            RichInput.compose(
                spoken: spoken, items: [item],
                words: spokenWords([0.4, 0.8, 1.2], endingClauseAt: [0, 1, 2])
            ),
            spoken
        )
    }

    func testTwoItemsAtTheSameMomentKeepTheirOrder() {
        let first = DictationItem(kind: .text, offset: 0.5, text: "FIRST")
        let second = DictationItem(kind: .url, offset: 0.5, text: "https://second")
        let composed = RichInput.compose(
            spoken: "one two", items: [first, second],
            words: spokenWords([0.5, 1.0], endingClauseAt: [0])
        )
        XCTAssertEqual(
            composed,
            "one\n\n<copied>\nFIRST\n</copied>\n\n<link>https://second</link>\n\ntwo"
        )
    }

    // MARK: - Split (cleanup and translation never touch inserted material)

    func testSplitCutsTheTextAtItsItems() {
        let item = DictationItem(kind: .text, offset: 0.5, text: "COPIED")
        let composed = RichInput.compose(
            spoken: "one two three", items: [item],
            words: spokenWords([0.5, 1.0, 1.5], endingClauseAt: [0])
        )
        let split = RichInput.split(composed, items: [item])

        XCTAssertFalse(split.isWhole)
        XCTAssertEqual(split.segments, ["one", "two three"])
        // The tags belong to the item, with the blank lines the composition
        // put around it — none of it is ever sent to the model.
        XCTAssertEqual(split.separators, ["\n\n<copied>\nCOPIED\n</copied>\n\n"])
    }

    func testReassemblyPutsTheItemBackByteIdentical() {
        let item = DictationItem(
            kind: .image, offset: 0.5, path: "/Users/a/Screenshot 2026-08-27 at 13.41.02.png"
        )
        let composed = RichInput.compose(
            spoken: "look at that", items: [item],
            words: spokenWords([0.5, 1.0, 1.5], endingClauseAt: [0])
        )
        let split = RichInput.split(composed, items: [item])
        let cleaned = split.reassembled(with: split.segments.map { $0.uppercased() })

        XCTAssertEqual(
            cleaned,
            """
            LOOK

            <screenshot>/Users/a/Screenshot 2026-08-27 at 13.41.02.png</screenshot>

            AT THAT
            """
        )
        XCTAssertTrue(cleaned.contains(item.pasteText!))
    }

    /// The model returning stray whitespace must not add a paragraph break: the
    /// whitespace at the seams belongs to the separators.
    func testReassemblyTrimsWhatTheModelReturns() {
        let item = DictationItem(kind: .text, offset: 0.5, text: "COPIED")
        let composed = RichInput.compose(
            spoken: "one two", items: [item], words: spokenWords([0.5, 1.0], endingClauseAt: [0])
        )
        let split = RichInput.split(composed, items: [item])

        XCTAssertEqual(split.reassembled(with: ["one\n", "  two\n\n"]), composed)
    }

    func testATextWithNoItemsSplitsIntoItself() {
        let split = RichInput.split("one two three", items: [])
        XCTAssertTrue(split.isWhole)
        XCTAssertEqual(split.segments, ["one two three"])
    }

    // MARK: - The entry carries them

    func testEntryRoundTripsItems() throws {
        var entry = DictationHistoryEntry(durationSeconds: 12)
        entry.status = .transcribed
        entry.rawText = "one COPIED two"
        entry.items = [
            DictationItem(kind: .text, offset: 0.5, text: "COPIED"),
            DictationItem(kind: .image, offset: 9.0, path: "/tmp/x-1.png", included: false),
        ]

        let data = try JSONEncoder().encode(entry)
        let decoded = try JSONDecoder().decode(DictationHistoryEntry.self, from: data)

        XCTAssertEqual(decoded.items?.count, 2)
        XCTAssertEqual(decoded.items?.first?.kind, .text)
        XCTAssertEqual(decoded.items?.first?.text, "COPIED")
        XCTAssertEqual(decoded.items?.last?.path, "/tmp/x-1.png")
        XCTAssertEqual(decoded.items?.last?.included, false)
        XCTAssertEqual(decoded, entry)
    }

    /// The bytes live in a file next to the entry; a second copy inside the
    /// JSON would be the same picture twice.
    func testImageBytesAreNotPersisted() throws {
        var entry = DictationHistoryEntry(durationSeconds: 4)
        entry.items = [
            DictationItem(kind: .image, offset: 1, path: "/tmp/x-0.png", imageData: Data([1, 2, 3]))
        ]
        let json = String(data: try JSONEncoder().encode(entry), encoding: .utf8)!

        XCTAssertFalse(json.contains("imageData"))
        XCTAssertNil(try JSONDecoder().decode(DictationHistoryEntry.self, from: Data(json.utf8))
            .items?.first?.imageData)
    }

    /// A dictation with nothing attached keeps its byte-identical JSON.
    func testAnEntryWithoutItemsWritesNoItemsKey() throws {
        let entry = DictationHistoryEntry(durationSeconds: 4)
        let json = String(data: try JSONEncoder().encode(entry), encoding: .utf8)!
        XCTAssertFalse(json.contains("items"))
    }
}
