import AppKit
import os

/// The clipboard door (#192): while a dictation records, anything the user
/// copies — text, an image, a file in Finder, a URL — and any screenshot sent to
/// the clipboard joins the prompt at the moment it happened.
///
/// macOS announces no pasteboard change, so this polls `changeCount` (the
/// cheapest read there is) and only touches the contents when it moved. The
/// bytes are read at once because the next copy overwrites them.
///
/// Three things never become an item: a copy marked concealed, transient or
/// auto-generated (every password manager marks its own — the surface does not
/// change at all, there is no "something was ignored" state), lore's own
/// pasteboard writes, and anything the classifier does not recognise.
@MainActor
final class ClipboardWatcher {
    private static let log = Logger(subsystem: "com.lore.app", category: "ClipboardWatcher")

    private let pasteboard: NSPasteboard
    private let interval: Duration
    private var task: Task<Void, Never>?
    private var lastChangeCount = 0

    /// `pasteboard` and `interval` are injectable so tests drive the loop
    /// against their own pasteboard without touching the user's clipboard.
    init(pasteboard: NSPasteboard = .general, interval: Duration = .milliseconds(100)) {
        self.pasteboard = pasteboard
        self.interval = interval
    }

    /// Watch until `stop()`. `offset` answers "how far into this dictation's
    /// audio is now" — the item carries the second of the speech it belongs to,
    /// not the second anything downstream noticed it.
    func start(
        offset: @escaping @MainActor () -> Double,
        onItem: @escaping @MainActor (DictationItem) -> Void
    ) {
        stop()
        // What was already on the clipboard when the recording began is not
        // something that happened during it.
        lastChangeCount = pasteboard.changeCount
        task = Task { [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(for: self?.interval ?? .milliseconds(100))
                guard let self, !Task.isCancelled else { return }
                if let item = self.collect(at: offset()) { onItem(item) }
            }
        }
    }

    func stop() {
        task?.cancel()
        task = nil
    }

    /// One poll. Internal so a test can step the loop instead of sleeping.
    func collect(at offset: Double) -> DictationItem? {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return nil }
        lastChangeCount = changeCount
        guard !PasteboardWriteLedger.shared.isOurs(changeCount) else { return nil }

        let types = pasteboard.types ?? []
        guard let kind = Self.kind(for: types) else { return nil }
        // `item.kind`, not `kind`: a copy that carries only plain text can
        // still turn out to be a link once the text itself is read.
        guard let item = read(kind: kind, at: offset) else { return nil }
        DiagStore.record(.dictationItemCollected(kind: item.kind, bytes: item.byteCount))
        Self.log.debug("clipboard item collected: \(item.kind.rawValue, privacy: .public)")
        return item
    }

    // MARK: - Classification

    /// The pasteboard types a copy carries, in the order the design fixed:
    /// file-url > image > url > text. Nil when nothing rides along — a
    /// concealed copy, or types lore has no form for.
    ///
    /// Pure and static so the whole table is testable without a pasteboard.
    static func kind(for types: [NSPasteboard.PasteboardType]) -> DictationItemKind? {
        let raw = Set(types.map(\.rawValue))
        guard raw.isDisjoint(with: concealedTypes) else { return nil }
        if raw.contains(NSPasteboard.PasteboardType.fileURL.rawValue) { return .fileURL }
        if !raw.isDisjoint(with: imageTypes) { return .image }
        if raw.contains(NSPasteboard.PasteboardType.URL.rawValue) { return .url }
        if raw.contains(NSPasteboard.PasteboardType.string.rawValue) { return .text }
        return nil
    }

    /// The nspasteboard.org convention every password manager that marks its
    /// copies uses (1Password, KeePassXC). A marked copy is never added, never
    /// shown, never counted.
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private static let imageTypes: Set<String> = [
        NSPasteboard.PasteboardType.png.rawValue,
        NSPasteboard.PasteboardType.tiff.rawValue,
    ]

    /// True when the copy is one http(s) address and nothing else. Half the
    /// "copy link" buttons on the web — Spotify's among them — write plain text
    /// and no `public.url`, so the pasteboard's own types cannot tell a link
    /// from a sentence; the characters can. Structure only: one line, no
    /// whitespace, a parseable absolute URL with a host. A sentence that
    /// mentions an address stays copied text.
    ///
    /// Pure and static so the rule is testable without a pasteboard.
    static func isLink(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, !trimmed.contains(where: \.isWhitespace),
              let url = URL(string: trimmed),
              let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https",
              let host = url.host(), !host.isEmpty
        else { return false }
        return true
    }

    // MARK: - Reading

    private func read(kind: DictationItemKind, at offset: Double) -> DictationItem? {
        switch kind {
        case .fileURL:
            guard let string = pasteboard.string(forType: .fileURL),
                  let path = URL(string: string)?.path, !path.isEmpty else { return nil }
            return DictationItem(kind: .fileURL, offset: offset, path: path)
        case .image:
            guard let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
                  !data.isEmpty else { return nil }
            return DictationItem(kind: .image, offset: offset, imageData: data)
        case .url:
            guard let string = pasteboard.string(forType: .URL) ?? pasteboard.string(forType: .string),
                  !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
            return DictationItem(kind: .url, offset: offset, text: string)
        case .text:
            guard let string = pasteboard.string(forType: .string),
                  !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
            return DictationItem(
                kind: Self.isLink(string) ? .url : .text, offset: offset, text: string
            )
        }
    }
}
